# Generated by Django 4.0.4 on 2022-05-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_created', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_menu_created', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='restaurants.restaurants', verbose_name='Restaurant')),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_menu_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
            ],
            options={
                'db_table': 'restaurant_menu',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurantmenu',
            index=models.Index(fields=['date'], name='restaurant__date_7606d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantmenu',
            unique_together={('name', 'restaurant')},
        ),
    ]
