# Generated by Django 4.0.4 on 2022-05-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('total_vote', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_restaurant', to='restaurants.restaurants', verbose_name='Restaurant')),
            ],
            options={
                'db_table': 'winner_restaurant',
                'ordering': ['-total_vote'],
            },
        ),
        migrations.AddIndex(
            model_name='winnerrestaurant',
            index=models.Index(fields=['date'], name='winner_rest_date_8b98cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='winnerrestaurant',
            unique_together={('restaurant', 'date')},
        ),
    ]
