# Generated by Django 4.0.4 on 2022-05-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_winnerrestaurant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantmenu',
            unique_together={('name', 'restaurant', 'date')},
        ),
    ]
